import React, { useState, useEffect } from 'react';
import { getSuggestedRoles, getSuggestedRolesByResumeId } from '../services/api';
import RoleCard from './RoleCard';
import RoleFilterControls from './RoleFilterControls';

/**
 * Master AI Role Intelligence dashboard container.
 * Fetches, filters, and renders top target job recommendations generated by LLM analysis.
 */
export function SuggestedRolesView({ scanId, resumeId }) {
  const [roles, setRoles] = useState([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);
  const [searchQuery, setSearchQuery] = useState('');
  const [minScore, setMinScore] = useState(0);

  useEffect(() => {
    let isMounted = true;
    async function fetchRoles() {
      if (!scanId && !resumeId) {
        setRoles([]);
        return;
      }

      setLoading(true);
      setError(null);

      try {
        let data = [];
        if (scanId) {
          data = await getSuggestedRoles(scanId);
        } else if (resumeId) {
          data = await getSuggestedRolesByResumeId(resumeId);
        }

        if (isMounted) {
          setRoles(data || []);
        }
      } catch (err) {
        if (isMounted) {
          logError('Failed fetching AI suggested roles', err);
          setError(err.message || 'Could not load suggested roles.');
        }
      } finally {
        if (isMounted) {
          setLoading(false);
        }
      }
    }

    fetchRoles();
    return () => { isMounted = false; };
  }, [scanId, resumeId]);

  function logError(msg, err) {
    console.error(msg, err);
  }

  // Filter roles based on search query and minimum score
  const filteredRoles = roles.filter((r) => {
    const scorePct = Math.round((r.confidenceScore || 0) * 100);
    if (scorePct < minScore) return false;

    if (!searchQuery.trim()) return true;
    const query = searchQuery.toLowerCase();
    const matchesTitle = r.roleTitle?.toLowerCase().includes(query);
    const matchesSkills = r.keySkills?.some((skill) => skill.toLowerCase().includes(query));
    return matchesTitle || matchesSkills;
  });

  return (
    <div
      className="card-glow animate-fade-in"
      style={{
        background: 'var(--color-bg-surface)',
        borderRadius: 'var(--radius-lg)',
        border: '1px solid var(--color-border)',
        padding: '24px',
        marginTop: '16px'
      }}
    >
      {/* Header section */}
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '18px' }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: '10px' }}>
          <span style={{ fontSize: '20px' }}>🤖</span>
          <div>
            <h2 style={{ fontSize: '18px', fontWeight: 700, color: '#ffffff', margin: 0 }}>
              AI Role Intelligence & Recommendations
            </h2>
            <p style={{ fontSize: '12px', color: 'var(--color-text-muted)', margin: 0, marginTop: '2px' }}>
              Phase 3 — Automated candidate target job matching powered by LLM text analysis
            </p>
          </div>
        </div>

        <span style={{
          fontSize: '11px',
          padding: '4px 10px',
          borderRadius: '9999px',
          background: 'rgba(99, 102, 241, 0.15)',
          color: 'var(--color-accent-light)',
          border: '1px solid rgba(99, 102, 241, 0.3)',
          fontWeight: 600
        }}>
          Phase 3 Active
        </span>
      </div>

      {/* Loading state */}
      {loading && (
        <div style={{ padding: '32px', textAlign: 'center', color: 'var(--color-text-muted)' }}>
          <div className="spinner" style={{ margin: '0 auto 12px auto' }}></div>
          <p style={{ fontSize: '14px' }}>Analyzing candidate experience & extracting target job roles...</p>
        </div>
      )}

      {/* Error state */}
      {error && !loading && (
        <div style={{
          padding: '16px',
          borderRadius: 'var(--radius-md)',
          background: 'rgba(239, 68, 68, 0.1)',
          border: '1px solid rgba(239, 68, 68, 0.3)',
          color: '#f87171',
          fontSize: '13px'
        }}>
          ⚠️ {error}
        </div>
      )}

      {/* Content state */}
      {!loading && !error && (
        <>
          {roles.length === 0 ? (
            <div style={{
              padding: '32px 16px',
              textAlign: 'center',
              background: 'rgba(30, 41, 59, 0.3)',
              borderRadius: 'var(--radius-md)',
              border: '1px border-dashed var(--color-border)',
              color: 'var(--color-text-muted)'
            }}>
              <p style={{ fontSize: '14px', margin: 0 }}>
                No AI role suggestions available yet. Upload a resume to trigger async processing.
              </p>
            </div>
          ) : (
            <>
              {/* Filter controls */}
              <RoleFilterControls
                searchQuery={searchQuery}
                onSearchChange={setSearchQuery}
                minScore={minScore}
                onMinScoreChange={setMinScore}
                totalCount={roles.length}
                filteredCount={filteredRoles.length}
              />

              {/* Roles grid */}
              <div style={{
                display: 'grid',
                gridTemplateColumns: 'repeat(auto-fill, minmax(280px, 1fr))',
                gap: '16px'
              }}>
                {filteredRoles.map((role, idx) => (
                  <RoleCard key={idx} role={role} />
                ))}
              </div>
            </>
          )}
        </>
      )}
    </div>
  );
}

export default SuggestedRolesView;
