import React, { useState, useEffect } from 'react';
import { getSuggestedRoles, getSuggestedRolesByResumeId } from '../services/api';
import RoleCard from './RoleCard';
import RoleFilterControls from './RoleFilterControls';

/**
 * Master AI Role Intelligence dashboard container.
 * Fetches, filters, and renders top target job recommendations generated by LLM analysis.
 */
export function SuggestedRolesView({ scanId, resumeId, scanStatus }) {
  const [roles, setRoles] = useState([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);
  const [searchQuery, setSearchQuery] = useState('');
  const [minScore, setMinScore] = useState(0);

  useEffect(() => {
    let isMounted = true;
    async function fetchRoles() {
      if (!scanId && !resumeId) {
        setRoles([]);
        return;
      }

      setLoading(true);
      setError(null);

      try {
        let data = [];
        if (scanId) {
          data = await getSuggestedRoles(scanId);
        }
        
        // Fallback: If scanId returned 0 roles (e.g. duplicate upload or ongoing scan), fetch by resumeId
        if ((!data || data.length === 0) && resumeId) {
          data = await getSuggestedRolesByResumeId(resumeId);
        }

        if (isMounted) {
          setRoles(data || []);
        }
      } catch (err) {
        if (isMounted) {
          console.error('Failed fetching AI suggested roles', err);
          setError(err.message || 'Could not load suggested roles.');
        }
      } finally {
        if (isMounted) {
          setLoading(false);
        }
      }
    }

    fetchRoles();
    return () => { isMounted = false; };
  }, [scanId, resumeId, scanStatus]);

  // Filter roles based on search query and minimum score
  const filteredRoles = roles.filter((r) => {
    const scorePct = Math.round((r.confidenceScore || 0) * 100);
    if (scorePct < minScore) return false;

    if (!searchQuery.trim()) return true;
    const query = searchQuery.toLowerCase();
    const matchesTitle = r.roleTitle?.toLowerCase().includes(query);
    const matchesSkills = r.keySkills?.some((skill) => skill.toLowerCase().includes(query));
    return matchesTitle || matchesSkills;
  });

  return (
    <div
      className="asana-card animate-fade-in"
      style={{
        padding: '24px',
        marginTop: '20px',
        background: 'var(--color-surface)',
        borderColor: 'var(--color-border)',
        borderRadius: 'var(--radius-md)'
      }}
    >
      {/* Header section */}
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '20px', flexWrap: 'wrap', gap: '12px' }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: '12px' }}>
          <div style={{
            width: '38px',
            height: '38px',
            borderRadius: 'var(--radius-md)',
            background: 'var(--status-purple-bg)',
            color: 'var(--status-purple-text)',
            border: '1px solid var(--status-purple-border)',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            fontSize: '20px'
          }}>
            🤖
          </div>
          <div>
            <h2 style={{ fontSize: '18px', fontWeight: 600, color: 'var(--color-text)', margin: 0 }}>
              AI Role Intelligence & Recommendations
            </h2>
            <p style={{ fontSize: '13px', color: 'var(--color-text-muted)', margin: 0, marginTop: '2px' }}>
              Phase 3 — Automated candidate target job matching powered by LLM text analysis
            </p>
          </div>
        </div>

        <span style={{
          fontSize: '11px',
          padding: '4px 12px',
          borderRadius: '9999px',
          background: 'var(--status-purple-bg)',
          color: 'var(--status-purple-text)',
          border: '1px solid var(--status-purple-border)',
          fontWeight: 600,
          letterSpacing: '0.03em'
        }}>
          Phase 3 Active
        </span>
      </div>

      {/* Loading state */}
      {loading && (
        <div style={{ padding: '32px', textAlign: 'center', color: 'var(--color-text-muted)' }}>
          <div className="spinner" style={{ margin: '0 auto 12px auto' }}></div>
          <p style={{ fontSize: '14px' }}>Analyzing candidate experience & extracting target job roles...</p>
        </div>
      )}

      {/* Error state */}
      {error && !loading && (
        <div style={{
          padding: '16px',
          borderRadius: 'var(--radius-md)',
          background: 'var(--status-rose-bg)',
          border: '1px solid var(--status-rose-border)',
          color: 'var(--status-rose-text)',
          fontSize: '13px'
        }}>
          ⚠️ {error}
        </div>
      )}

      {/* Content state */}
      {!loading && !error && (
        <>
          {roles.length === 0 ? (
            <div style={{
              padding: '32px 16px',
              textAlign: 'center',
              background: 'var(--color-background-subtle)',
              borderRadius: 'var(--radius-md)',
              border: '1px dashed var(--color-border)',
              color: 'var(--color-text-muted)'
            }}>
              <p style={{ fontSize: '14px', margin: 0 }}>
                {(scanStatus === 'PROCESSING' || scanStatus === 'PENDING')
                  ? '🤖 Background AI Pipeline is currently extracting target job roles...'
                  : 'No AI role suggestions available yet. Upload a resume to trigger async processing.'}
              </p>
            </div>
          ) : (
            <>
              {/* Filter controls */}
              <RoleFilterControls
                searchQuery={searchQuery}
                onSearchChange={setSearchQuery}
                minScore={minScore}
                onMinScoreChange={setMinScore}
                totalCount={roles.length}
                filteredCount={filteredRoles.length}
              />

              {/* Roles grid */}
              <div style={{
                display: 'grid',
                gridTemplateColumns: 'repeat(auto-fill, minmax(300px, 1fr))',
                gap: '16px'
              }}>
                {filteredRoles.map((role, idx) => (
                  <RoleCard key={idx} role={role} />
                ))}
              </div>
            </>
          )}
        </>
      )}
    </div>
  );
}

export default SuggestedRolesView;
